spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/barber_shop_bbdd}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update

  devtools:
    restart:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 465 #587 o 465 o 25
    username: amsdevtech@gmail.com
    password: mcfryptbdhpnsucm
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true  # SSL directo en lugar de STARTTLS
            trust: smtp.gmail.com
        connectiontimeout: 10000
        timeout: 10000
app:
  mail:
    from: amsdevtech@gmail.com
    fromName: Barber Shop APP
  base-url: http://localhost:8080

server:
  port: 8080